<template>
  <div class="grid-container">
    <div class="grid-x grid-margin-x">
      <div class="cell">
        <h1>Mitrans Test</h1>
        <p>
          Product we're selling is below.
          <br>Send as much information as possible to Midtrans.
          <br>
          Cost of item is IDR {{ product.total.toLocaleString() }} which is in the currency Midtrans needs.
          <br>Adjust as needed.
        </p>
        <pre>{{ product }}</pre>
        <p>
          <button
            class="button primary"
            v-on:click="payWithMidtrans"
          >Pay IDR {{ product.total.toLocaleString() }}</button>
        </p>
      </div>
    </div>
  </div>
</template>

<script>
import moment from 'moment'
import { SNAP_TOKEN_URL, NOTIF_HANDLER_URL } from '../lib/apis.js'
import axios from 'axios'
import setHeaders from '../lib/setHeaders.js'
export default {
  name: 'home',
  metaInfo: {
    title: 'Toorhop — Midtrans'
  },
  data () {
    return {
      product: {
        tour: 'Brooklyn Bridge Tour',
        name: 'Brooklyn Bridge Tour',
        description:
          'New Booking: Brooklyn Bridge Tour / December 25, 2019 / 4 / BOOKING_KEY',
        bookingKey: 'BOOKING_KEY',
        guideKey: 'GUIDE_KEY',
        tourKey: 'TOUR_KEY',
        travelerKey: 'TRAVELER_KEY',
        guideName: 'Spiderman',
        travelerName: 'Batman',
        requestedDate: '2019-12-25T12:00:00+7:00',
        adults: 4,
        total: 100000
      },
      showModal: false,
      orderDetail: {}
    }
  },
  methods: {
    async payWithMidtrans () {
      /**
       * customer details
       * info of your costumers
       */
      const customerDetails = {
        email: 'example@example.com',
        first_name: 'first_name',
        last_name: 'last_name',
        phone: '08123456789'
      }

      /**
       * Array of your product detail to be sell
       */
      const itemDetails = [
        {
          id: moment().unix(),
          price: 25000,
          quantity: 4,
          name: this.product.name
        }
      ]

      /**
       * order_id as generated by your system
       */
      const orderId = moment().unix()

      const transactionDetails = {
        customer_details: customerDetails,
        item_details: itemDetails,
        order_id: orderId
      }
      // console.log('transactionDetail', transactionDetail)

      try {
        const headers = await setHeaders()
        const resp = await axios
          .post(SNAP_TOKEN_URL, transactionDetails, {
            headers
          })
          .then(res => res.data)
        if (resp.meta.status === 200) {
          const { transactionToken } = resp.data
          // Open Snap popup with defined callbacks.
          // eslint-disable-next-line no-undef
          snap.pay(transactionToken, {
            onSuccess: function (result) {
              axios.post(NOTIF_HANDLER_URL, result)
              console.log('SUCCESS', result)
            },
            onPending: function (result) {
              axios.post(NOTIF_HANDLER_URL, result)
              console.log('Payment pending', result)
            },
            onError: function () {
              // TODO: parse error properly
              console.log('Payment error')
            }
          })
        }
      } catch (e) {
        console.log('e', e)
      }
    }
  }
}
</script>

<style lang="scss" scoped>
</style>
